name: frontend
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.6
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.5
  get: ^4.6.6
  image_picker: ^1.0.7
  google_mlkit_face_detection: ^0.12.0
  google_ml_kit: ^0.19.0
  firebase_app_check: ^0.3.2+3
  http: ^1.3.0
  google_mlkit_smart_reply: ^0.12.0
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_translation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/onboarding_images/
    - assets/fonts/
    - assets/images/login_signup/login.png
    - assets/images/login_signup/profile.jpg
    - assets/images/logo/
    - assets/images/messages/error_sign.png
    - assets/images/messages/red_bubble.png
    - assets/images/messages/close_icon.png
    - assets/images/messages/check_sign.png
    - assets/images/messages/green_bubble.png


  fonts:
    - family: Oleo
      fonts:
        - asset: assets/fonts/OleoScriptSwashCaps-Bold.ttf
          weight: 700
        - asset: assets/fonts/OleoScriptSwashCaps-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Aboreto
      fonts:
        - asset: assets/fonts/Aboreto-Regular.ttf
          weight: 400
  
  
  
